Fit_daily:    Prog/fit_daily.c
	gcc -O2  Prog/fit_daily.c  -Wall  -llapack   -o fit_day
Fit_hourly:   Prog/fit_hourly.c
	gcc -O2  Prog/fit_hourly.c  -Wall  -llapack   -o fit_hour
Fit_hourly_rmp:   Prog/fit_hourly_rmp.c
	gcc -O2  Prog/fit_hourly_rmp.c   -Wall  -llapack   -o fit_hour
Fit_example:  Prog/fit_example.c
	gcc -O2  Prog/fit_example.c   -Wall  -llapack   -o fit_ex
Fit_example_rmp:  Prog/fit_example_rmp.c
	gcc -O2  Prog/fit_example_rmp.c   -Wall  -llapack   -o fit_ex_rmp
