Pred_Bayes_cum:    Prog/pred_Bayes_Err_cum.c 
	gcc -O2  Prog/pred_Bayes_Err_cum.c   -llapack  -Wall  -o  Pred_Prop
Pred_Bayes_ts:    Prog/pred_Bayes_Err_ts.c
	gcc -O2  Prog/pred_Bayes_Err_ts.c   -llapack  -Wall  -o  Pred_Prop
Pred_Bayes_ex:    Prog/pred_Bayes_example.c
	gcc -O2  Prog/pred_Bayes_example.c   -llapack  -Wall  -o  Pred_Prop
Prior:       Prog/calc_prior.c
	gcc -O2  Prog/calc_prior.c  -Wall
